#!/bin/sh
#
# goshd - this script starts and stops the goshd-server daemon
#
# chkconfig:   - 85 15 
# description:  goshd is a persistent key-value database
# processname: goshd-server
# config:      /etc/goshd/goshd.conf
# config:      /etc/sysconfig/goshd
# pidfile:     /var/run/goshd.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

goshd="/usr/bin/goshd"
pidfile="/var/run/goshd.pid"
prog=$(basename $goshd)

start() {
    echo "start"
    [ -x $goshd ] || exit 5
    echo -n $"Starting $prog: "
    daemon --pidfile ${pidfile} $goshd &
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc $goshd -HUP
    RETVAL=$?
    echo
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
	    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload}"
        exit 2
esac
